import logging

from state import AgentState
from tools.github import GitHubClient
from tools.git_ops import create_branch_and_commit, ensure_repo_cloned

log = logging.getLogger(__name__)

_github = GitHubClient()


def preflight(state: AgentState) -> dict:
    """Ensures the target repo is cloned locally before any LLM work begins."""
    try:
        ensure_repo_cloned(state["repo_name"], state["local_repo_path"])
    except Exception as exc:
        return {"status": "preflight_failed", "preflight_error": str(exc)}
    return {}


def read_github_issue(state: AgentState) -> dict:
    """Fetches issue details from GitHub API.

    Returns formatted issue title and body, initializes retry_count and max_retries.
    """
    log.info("Fetching GitHub issue #%d from %s...", state["issue_number"], state["repo_name"])
    api_response = _github.fetch_issue(state["repo_name"], state["issue_number"])
    log.info("Issue fetched: %s", api_response["title"])
    return {
        "issue_details": f"Title: {api_response['title']}\nBody: {api_response['body']}",
        "retry_count": 0,
        "max_retries": 3,
    }


def create_pr(state: AgentState) -> dict:
    """Commits the solution and opens a pull request."""
    if state.get("pr_url"):
        log.info("PR already created at %s — skipping.", state["pr_url"])
        return {"status": "pr_created"}

    branch_name = f"fix/issue-{state['issue_number']}"
    log.info("Committing code and opening PR on branch '%s'...", branch_name)

    create_branch_and_commit(
        local_repo_path=state["local_repo_path"],
        branch_name=branch_name,
        base_branch=state["base_branch"],
        modified_files=state.get("modified_files", []),
    )

    pr_url = _github.open_pull_request(
        repo_name=state["repo_name"],
        branch_name=branch_name,
        base_branch=state["base_branch"],
        title=f"fix: resolve issue #{state['issue_number']}",
        body=f"Closes #{state['issue_number']}\n\nGenerated by the story-pr-agent.",
    )
    log.info("PR ready: %s", pr_url)
    return {"status": "pr_created", "pr_url": pr_url}


def handle_failure(state: AgentState) -> dict:
    """Terminal node for all failure paths: preflight failures and max-retry exhaustion."""
    if state.get("status") == "preflight_failed":
        log.error("Preflight failed — aborting before any LLM work.\n%s", state.get("preflight_error", ""))
        print(f"\n[story-pr-agent] Preflight check failed:\n  {state.get('preflight_error', '')}\n")
    else:
        log.error(
            "Agent failed to produce a passing solution after %d attempts. Last error:\n%s",
            state.get("retry_count", 0),
            state.get("test_results", "unknown"),
        )
    return {"status": "failed"}
