import logging

from state import AgentState
from tools.github import fetch_issue_from_github, open_pull_request
from tools.git_ops import create_branch_and_commit

log = logging.getLogger(__name__)


def read_repo_source_code(state: AgentState)-> dict:
    return {}

def read_github_issue(state: AgentState) -> dict:
    """Fetches issue details from GitHub API.

    Returns formatted issue title and body, initializes retry_count and max_retries.
    """
    log.info("Fetching GitHub issue #%d from %s...", state["issue_number"], state["repo_name"])
    api_response = fetch_issue_from_github(state["repo_name"], state["issue_number"])
    log.info("Issue fetched: %s", api_response["title"])
    return {
        "issue_details": f"Title: {api_response['title']}\nBody: {api_response['body']}",
        "retry_count": 0,
        "max_retries": 3,
    }


def create_pr(state: AgentState) -> dict:
    """Creates a new branch, commits solution code, and opens a GitHub pull request.

    Branch name format: fix/issue-{issue_number}
    Returns the opened PR URL.
    """
    branch_name = f"fix/issue-{state['issue_number']}"
    filename = f"solution_issue_{state['issue_number']}.py"
    log.info("Committing code and creating PR on branch '%s'...", branch_name)

    create_branch_and_commit(
        local_repo_path=state["local_repo_path"],
        branch_name=branch_name,
        base_branch=state["base_branch"],
        code=state["code_snippet"],
        filename=filename,
    )

    pr_url = open_pull_request(
        repo_name=state["repo_name"],
        branch_name=branch_name,
        base_branch=state["base_branch"],
        title=f"fix: resolve issue #{state['issue_number']}",
        body=f"Closes #{state['issue_number']}\n\nGenerated by the story-pr-agent.",
    )
    log.info("PR ready: %s", pr_url)
    return {"status": "pr_created", "pr_url": pr_url}


def handle_failure(state: AgentState) -> dict:
    """Logs failure details when max retries are exceeded.

    This is the terminal node for failed solution attempts.
    """
    log.error(
        "Agent failed to produce a passing solution after %d attempts. Last error:\n%s",
        state["retry_count"],
        state.get("test_results", "unknown"),
    )
    return {"status": "failed"}
