import logging
import subprocess

from state import AgentState
from tools.github import (
    check_github_permissions,
    create_draft_pr,
    fetch_issue_from_github,
    update_pull_request,
)
from tools.git_ops import create_branch_and_commit, push_empty_branch

log = logging.getLogger(__name__)


def preflight(state: AgentState) -> dict:
    """Checks GitHub permissions and ast-grep availability before any real work begins.

    GitHub: verifies token scopes, pushes an empty branch, and creates a draft PR
    to confirm end-to-end push + PR creation rights.

    ast-grep: confirms the CLI is on PATH.

    On any failure sets status='preflight_failed' with a friendly preflight_error message,
    which route_after_preflight immediately routes to fail_state.
    On success, stores preflight_pr_number so create_pr can promote it instead of
    opening a new PR.
    """
    branch_name = f"fix/issue-{state['issue_number']}"

    perm_error = check_github_permissions()
    if perm_error:
        return {"status": "preflight_failed", "preflight_error": f"GitHub permissions: {perm_error}"}

    try:
        push_empty_branch(state["local_repo_path"], branch_name, state["base_branch"])
    except Exception as exc:
        return {
            "status": "preflight_failed",
            "preflight_error": f"GitHub push failed — check repo write access: {exc}",
        }

    try:
        pr_number = create_draft_pr(state["repo_name"], branch_name, state["base_branch"])
    except Exception as exc:
        return {
            "status": "preflight_failed",
            "preflight_error": f"GitHub draft PR creation failed — check pull_requests permission: {exc}",
        }

    try:
        subprocess.run(
            ["ast-grep", "--version"],
            capture_output=True, check=True, timeout=10,
        )
    except FileNotFoundError:
        return {
            "status": "preflight_failed",
            "preflight_error": "ast-grep not found — install with: npm install -g @ast-grep/cli",
        }
    except Exception as exc:
        return {"status": "preflight_failed", "preflight_error": f"ast-grep check failed: {exc}"}

    log.info("Preflight passed — draft PR #%d ready on branch '%s'.", pr_number, branch_name)
    return {"preflight_pr_number": pr_number}

def read_github_issue(state: AgentState) -> dict:
    """Fetches issue details from GitHub API.

    Returns formatted issue title and body, initializes retry_count and max_retries.
    """
    log.info("Fetching GitHub issue #%d from %s...", state["issue_number"], state["repo_name"])
    api_response = fetch_issue_from_github(state["repo_name"], state["issue_number"])
    log.info("Issue fetched: %s", api_response["title"])
    return {
        "issue_details": f"Title: {api_response['title']}\nBody: {api_response['body']}",
        "retry_count": 0,
        "max_retries": 3,
    }


def create_pr(state: AgentState) -> dict:
    """Pushes the real solution onto the preflight branch and promotes the draft PR.

    Branch name format: fix/issue-{issue_number} (same branch created by preflight).
    Promotes the existing draft PR (preflight_pr_number) to a ready PR instead of
    opening a new one, preserving the PR URL from the preflight step.
    """
    branch_name = f"fix/issue-{state['issue_number']}"
    log.info("Committing code and promoting draft PR on branch '%s'...", branch_name)

    create_branch_and_commit(
        local_repo_path=state["local_repo_path"],
        branch_name=branch_name,
        base_branch=state["base_branch"],
        modified_files=state.get("modified_files", []),
    )

    title = f"fix: resolve issue #{state['issue_number']}"
    body  = f"Closes #{state['issue_number']}\n\nGenerated by the story-pr-agent."

    pr_url = update_pull_request(
        repo_name=state["repo_name"],
        pr_number=state["preflight_pr_number"],
        title=title,
        body=body,
    )
    log.info("PR ready: %s", pr_url)
    return {"status": "pr_created", "pr_url": pr_url}


def handle_failure(state: AgentState) -> dict:
    """Terminal node for all failure paths: preflight failures and max-retry exhaustion."""
    if state.get("status") == "preflight_failed":
        log.error("Preflight failed — aborting before any LLM work.\n%s", state.get("preflight_error", ""))
        print(f"\n[story-pr-agent] Preflight check failed:\n  {state.get('preflight_error', '')}\n")
    else:
        log.error(
            "Agent failed to produce a passing solution after %d attempts. Last error:\n%s",
            state.get("retry_count", 0),
            state.get("test_results", "unknown"),
        )
    return {"status": "failed"}
